- name: Install dependencies and configure the application
  hosts: all
  tasks:
    - name: Install system dependencies
      apt:
        name: 
          - curl
          - redis-server  # Installez Redis si nécessaire, ajustez pour votre distribution Linux
        state: present

    - name: Copy application files
      copy:
        src: "C:\Users\adri2\voting-app\app.py"
        dest: /app
      become: true

    - name: Install Python dependencies
      pip:
        requirements: /app/requirements.txt

    - name: Set environment variables
      lineinfile:
        path: /app/.env
        line: "{{ item.key }}={{ item.value }}"
      loop:
        - { key: "REDIS", value: "redis" }
        - { key: "REDIS_PWD", value: "12345" }