version: "3"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_redis_password_here  # Remplacez par le mot de passe Redis
    networks:
      - voting-app-network

  voting-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - REDIS=redis  # Le nom du service Redis dans le réseau Docker Compose
      - REDIS_PWD=your_redis_password_here  # Remplacez par le mot de passe Redis
    networks:
      - voting-app-network
    depends_on:
      - redis

networks:
  voting-app-network:
    driver: bridge
